CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL')
  TIMESTAMP_FORMAT = 'DD-MM-YYYY HH24:MI:SS';


CREATE OR REPLACE STAGE FOOD_STAGE
FILE_FORMAT = CSV_FORMAT;


COPY INTO DIM_CUSTOMER
FROM @FOOD_STAGE/dim_customer.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO DIM_DELIVERY_PARTNER
FROM @FOOD_STAGE/dim_delivery_partner_.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO DIM_RESTAURANT
FROM @FOOD_STAGE/dim_restaurant.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO DIM_MENU_ITEM
FROM @FOOD_STAGE/dim_menu_item.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO FACT_ORDERS
FROM @FOOD_STAGE/fact_orders.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO FACT_ORDER_ITEMS
FROM @FOOD_STAGE/fact_order_items.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO FACT_DELIVERY_PERFORMANCE
FROM @FOOD_STAGE/fact_delivery_performance.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');

COPY INTO FACT_RATINGS
FROM @FOOD_STAGE/fact_ratings.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT');