WITH customer_spend AS (
    SELECT
        CUSTOMER_ID,
        SUM(TOTAL_AMOUNT) AS TOTAL_SPEND
    FROM FACT_ORDERS
    WHERE ORDER_TIMESTAMP < '2025-04-01'
    GROUP BY CUSTOMER_ID
),

high_value_customers AS (
    SELECT
        CUSTOMER_ID,
        TOTAL_SPEND
    FROM customer_spend
    QUALIFY PERCENT_RANK() OVER (ORDER BY TOTAL_SPEND) >= 0.95
),

pre_crisis_metrics AS (
    SELECT
        o.CUSTOMER_ID,
        COUNT(DISTINCT o.ORDER_ID) AS PRE_CRISIS_ORDERS,
        AVG(r.RATING) AS PRE_CRISIS_RATING
    FROM FACT_ORDERS o
    LEFT JOIN FACT_RATINGS r
        ON o.ORDER_ID = r.ORDER_ID
    WHERE o.ORDER_TIMESTAMP < '2025-04-01'
    GROUP BY o.CUSTOMER_ID
),

crisis_metrics AS (
    SELECT
        o.CUSTOMER_ID,
        COUNT(DISTINCT o.ORDER_ID) AS CRISIS_ORDERS,
        AVG(r.RATING) AS CRISIS_RATING
    FROM FACT_ORDERS o
    LEFT JOIN FACT_RATINGS r
        ON o.ORDER_ID = r.ORDER_ID
    WHERE o.ORDER_TIMESTAMP BETWEEN '2025-04-01' AND '2025-04-30'
    GROUP BY o.CUSTOMER_ID
),

customer_decline AS (
    SELECT
        h.CUSTOMER_ID,
        h.TOTAL_SPEND,

        p.PRE_CRISIS_ORDERS,
        COALESCE(c.CRISIS_ORDERS,0) AS CRISIS_ORDERS,

        p.PRE_CRISIS_RATING,
        c.CRISIS_RATING,

        p.PRE_CRISIS_ORDERS -
        COALESCE(c.CRISIS_ORDERS,0)
            AS ORDER_DROP,

        p.PRE_CRISIS_RATING -
        COALESCE(c.CRISIS_RATING,0)
            AS RATING_DROP

    FROM high_value_customers h
    JOIN pre_crisis_metrics p
        ON h.CUSTOMER_ID = p.CUSTOMER_ID
    LEFT JOIN crisis_metrics c
        ON h.CUSTOMER_ID = c.CUSTOMER_ID
)

SELECT *
FROM customer_decline
ORDER BY
    ORDER_DROP DESC,
    RATING_DROP DESC;