WITH negative_reviews AS (
    SELECT
        LOWER(REVIEW_TEXT) AS REVIEW_TEXT
    FROM FACT_RATINGS
    WHERE REVIEW_TIMESTAMP BETWEEN '2025-04-01' AND '2025-04-30'
      AND (RATING <= 2 OR SENTIMENT_SCORE < 0)
)

SELECT REVIEW_TEXT
FROM negative_reviews;